name: Wake Up Streamlit App

on:
  schedule:
    # Chạy mỗi 30 phút để cho app có nhiều thời gian khởi động hơn
    - cron: '*/30 * * * *'

jobs:
  wake_up:
    runs-on: ubuntu-latest
    steps:
      - name: Send GET request to Streamlit app
        run: |
          curl --fail "https://duoc-dien-ai-laz8nqrjyz4arbpqum6nxv.streamlit.app/" || exit 0
