name: Wake Up Streamlit App

on:
  schedule:
    # Chạy mỗi 30 phút một lần
    - cron: '*/30 * * * *'

jobs:
  wake_up:
    runs-on: ubuntu-latest
    steps:
      - name: Gửi yêu cầu GET đến ứng dụng Streamlit và chờ
        run: |
          curl -L --fail "https://duoc-dien-ai-laz8nqrjyz4arbpqum6nxv.streamlit.app" || exit 0
